# .goreleaser.yml
version: 2
project_name: healthcheck-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/healthcheck/main.go
    binary: healthcheck
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Adicionar flags específicas para sqlite3
    flags:
      - -tags=sqlite3
    ldflags:
      - -s -w -X main.version={{.Version}}
    # Configurar dependências do sistema para cada OS
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - test-config.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: renancavalcantercb
    name: healthcheck-cli